# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9e5cf827f23a5999b46a0914c4a5b4e0084bc9f7a9b6fac25698581af99e651ca76cdaceb16326e66a2303c7817aa09f77d017dc6b02d06a0cac8ad2c48ecdb

test:
  secret_key_base: a85db9b2aceea580f9d3823047cc521061ef8404a3d370b7414c7b72a1318c88a461635de16a7382cc1fbce6ca68c3edc3b49d6815d77a7be81dd7e99ed5d335

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
